Tracker/Tracker/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from Tracker import views

urlpatterns = [
    url(r'^$', views.login_redirect, name ='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include('login.urls')),
    url(r'^mobile/', include('mobile.urls')),
    url(r'^general/', include('general.urls')),
    url(r'^others/', include('others.urls')),
    url(r'^hahe/', include('hahe.urls')),
]

Tracker/hahe/urls.py
from django.conf.urls import url, include
from . import views
from hahe.views import (
ProductView, IntermediateView, DetailView, AddDeviceView, ExcelView, DetailExcelView, HomepageView, DeviceSummaryView,
HomepageHAView, HomepageHEView, DeviceSummaryHAView, DeviceSummaryHEView
)

urlpatterns = [
    url(r'^$', ProductView.as_view(), name='haheproduct'),
    url(r'^homepage/$', HomepageView.as_view(), name='haheHomepage'),
    url(r'^homepage/HA/$', HomepageHAView.as_view(), name='haheHomepageHA'),
    url(r'^homepage/HE/$', HomepageHEView.as_view(), name='haheHomepageHE'),
    url(r'^homepage/(?P<pk>\d+)/$', DeviceSummaryView.as_view(), name='DeviceSummary'),
    url(r'^homepage/HA/(?P<pk>\d+)/$', DeviceSummaryHAView.as_view(), name='DeviceSummaryHA'),
    url(r'^homepage/HE/(?P<pk>\d+)/$', DeviceSummaryHEView.as_view(), name='DeviceSummaryHE'),
    url(r'^(?P<pk>\d+)/$', IntermediateView.as_view(), name='haheintermediate'),
    url(r'^teams/(?P<id>\d+)/$', DetailView.as_view(), name='hahedetail'),
    url(r'^defaulttemplate/$', AddDeviceView.as_view(), name='haheAddDevice'),
    url(r'^excel/$', ExcelView.as_view(), name='haheExcel'),
    url(r'^(?P<pk>\d+)/detailexcel/$', DetailExcelView.as_view(), name='haheDetailExcel'),
]

Tracker/login/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib.auth.views import (
    login, logout, password_reset, password_reset_done, password_reset_confirm,
    password_reset_complete
)
from django.views.generic import ListView, DetailView
from login.models import Device
from login.views import (
    ProductReadinessView, IntermediateView, VideoContentView,DigitalContentView, CallCenterTrainingView,CallCenterOperationsView,
ProductSupportView, WarehouseView, FieldServiceView, TechSupportView, ServiceTrainingView, ServiceMarketingView,PartsView,
ProductView, DefaultSettingView, ExcelView,ExcelDetailView, HomepageView,DeviceSummaryView,HomepageHAView,HomepageHEView,
DeviceSummaryHAView,DeviceSummaryHEView, DeviceSummaryPRView,DeviceSummaryVCView, DeviceSummaryDCView,
DeviceSummaryCCTView,DeviceSummaryCCOView, DeviceSummaryWView, DeviceSummaryFSView, DeviceSummaryTSView, DeviceSummarySMView,
DeviceSummarySTView, DeviceSummaryPView
)

from django.contrib.auth.decorators import login_required

def required(wrapping_functions,patterns_rslt):
    '''
    Used to require 1..n decorators in any view returned by a url tree

    Usage:
      urlpatterns = required(func,patterns(...))
      urlpatterns = required((func,func,func),patterns(...))

    Note:
      Use functools.partial to pass keyword params to the required
      decorators. If you need to pass args you will have to write a
      wrapper function.

    Example:
      from functools import partial

      urlpatterns = required(
          partial(login_required,login_url='/accounts/login/'),
          patterns(...)
      )
    '''
    if not hasattr(wrapping_functions,'__iter__'):
        wrapping_functions = (wrapping_functions,)

    return [
        _wrap_instance__resolve(wrapping_functions,instance)
        for instance in patterns_rslt
    ]
def _wrap_instance__resolve(wrapping_functions,instance):
    if not hasattr(instance,'resolve'): return instance
    resolve = getattr(instance,'resolve')

    def _wrap_func_in_returned_resolver_match(*args,**kwargs):
        rslt = resolve(*args,**kwargs)

        if not hasattr(rslt,'func'):return rslt
        f = getattr(rslt,'func')

        for _f in reversed(wrapping_functions):
            # @decorate the function from inner to outter
            f = _f(f)

        setattr(rslt,'func',f)

        return rslt

    setattr(instance,'resolve',_wrap_func_in_returned_resolver_match)

    return instance

urlpatterns = [
    url(r'^$', views.home),
    url(r'^auth/$', login, {'template_name': 'login/login.html'}),
    url(r'^logout/$', logout, {'template_name': 'login/logout.html'}, name='logout'),
    url(r'^register/$', views.register, name = 'register'),
    url(r'^change-password/$', views.change_password, name='change_password'),
    url(r'^reset-password/$', password_reset, name='reset_password'),
    url(r'^excel/$', ExcelView.as_view(), name='excel'),
    url(r'^excel/(?P<pk>\d+)/$', ExcelDetailView.as_view(), name='excel'),
    url(r'^reset-password/done/$', password_reset_done, name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
        name='password_reset_confirm'),
    url(r'^defaultsetting/$', DefaultSettingView.as_view(), name='defaultsetting'),
    url(r'^homepage/$', HomepageView.as_view(), name='Homepage'),
    url(r'^homepage/HA/$', HomepageHAView.as_view(), name='HomepageHA'),
    url(r'^homepage/HE/$', HomepageHEView.as_view(), name='HomepageHE'),
    url(r'^homepage/(?P<pk>\d+)/$', DeviceSummaryView.as_view(), name='DeviceSummary'),
    url(r'^homepage/HA/(?P<pk>\d+)/$', DeviceSummaryHAView.as_view(), name='DeviceSummaryHA'),
    url(r'^homepage/HE/(?P<pk>\d+)/$', DeviceSummaryHEView.as_view(), name='DeviceSummaryHE'),
    url(r'^reset-password/complete/$', password_reset_complete, name='password_reset_complete'),
    # url(r'^summary/$', ListView.as_view(queryset=Device.objects.all().order_by("LaunchDate"),
    #                                     template_name = "login/summary.html")),
    url(r'^summary/$', ProductView.as_view(), name='product'),
    url(r'^summary/(?P<pk>\d+)/$', IntermediateView.as_view(), name='Intermediate'),
    url(r'^summary/(?P<pk>\d+)/productreadiness/$', ProductReadinessView.as_view(), name='ProductReadiness'),
    url(r'^summary/(?P<pk>\d+)/videocontent/$', VideoContentView.as_view(), name='videocontent'),
    url(r'^summary/(?P<pk>\d+)/digitalcontent/$', DigitalContentView.as_view(), name='digitalcontent'),
    url(r'^summary/(?P<pk>\d+)/callcentertraining/$', CallCenterTrainingView.as_view(), name='callcentertraining'),
    url(r'^summary/(?P<pk>\d+)/callcenteroperations/$', CallCenterOperationsView.as_view(), name='callcenteroperations'),
    url(r'^summary/(?P<pk>\d+)/productsupport/$', ProductSupportView.as_view(), name='productsupport'),
    url(r'^summary/(?P<pk>\d+)/warehouse/$', WarehouseView.as_view(), name='warehouse'),
    url(r'^summary/(?P<pk>\d+)/fieldservice/$', FieldServiceView.as_view(), name='fieldservice'),
    url(r'^summary/(?P<pk>\d+)/techsupport/$', TechSupportView.as_view(), name='techsupport'),
    url(r'^summary/(?P<pk>\d+)/servicemarketing/$', ServiceMarketingView.as_view(), name='servicemarketing'),
    url(r'^summary/(?P<pk>\d+)/servicetraining/$', ServiceTrainingView.as_view(),
        name='servicetraining'),
    url(r'^summary/(?P<pk>\d+)/parts/$', PartsView.as_view(), name='parts'),
    url(r'^homepage/(?P<pk>\d+)/productreadiness/$', DeviceSummaryPRView.as_view(), name='DeviceSummaryPR'),
    url(r'^homepage/(?P<pk>\d+)/videocontent/$', DeviceSummaryVCView.as_view(), name='DeviceSummaryVC'),
    url(r'^homepage/(?P<pk>\d+)/digitalcontent/$', DeviceSummaryDCView.as_view(), name='DeviceSummaryDC'),
    url(r'^homepage/(?P<pk>\d+)/callcentertraining/$', DeviceSummaryCCTView.as_view(), name='DeviceSummaryCCT'),
    url(r'^homepage/(?P<pk>\d+)/callcenteroperations/$', DeviceSummaryCCOView.as_view(), name='DeviceSummaryCCO'),
    url(r'^homepage/(?P<pk>\d+)/warehouse/$', DeviceSummaryWView.as_view(), name='DeviceSummaryW'),
    url(r'^homepage/(?P<pk>\d+)/fieldservice/$', DeviceSummaryFSView.as_view(), name='DeviceSummaryFS'),
    url(r'^homepage/(?P<pk>\d+)/techsupport/$', DeviceSummaryTSView.as_view(), name='DeviceSummaryTS'),
    url(r'^homepage/(?P<pk>\d+)/servicemarketing/$', DeviceSummarySMView.as_view(), name='DeviceSummarySM'),
    url(r'^homepage/(?P<pk>\d+)/servicetraining/$', DeviceSummarySTView.as_view(), name='DeviceSummaryST'),
    url(r'^homepage/(?P<pk>\d+)/parts/$', DeviceSummaryPView.as_view(), name='DeviceSummaryP'),

]

Tracker/hahe/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _

from django.db import models

# Create your models here.

class IntegerRangeField(models.IntegerField):
    def __init__(self, verbose_name=None, name=None, min_value=None, max_value=None, **kwargs):
        self.min_value, self.max_value = min_value, max_value
        models.IntegerField.__init__(self, verbose_name, name, **kwargs)
    def formfield(self, **kwargs):
        defaults = {'min_value': self.min_value, 'max_value':self.max_value}
        defaults.update(kwargs)
        return super(IntegerRangeField, self).formfield(**defaults)


class Announcements(models.Model):
    post = models.TextField(blank=True,default='')
    information = 'information'
    warning = 'warning'
    alert = 'alert'
    Status_Choice = (
        (information, 'information'),
        (warning, 'warning'),
        (alert, 'alert'),
    )

    Severity = models.CharField(max_length=20, choices=Status_Choice, default='information')


class Product(models.Model):
    Name = models.CharField(max_length=100, default = '')
    ProductDescription = models.CharField(max_length=100, default='')
    HE = 'HE'
    HA = 'HA'
    Device_Choice = (
        (HE, 'HE'),
        (HA, 'HA'),
    )
    Device_Category = models.CharField(max_length=10, choices=Device_Choice, default='')
    LaunchDate = models.DateField(blank=True, null=True)
    completed = IntegerRangeField(min_value=0, max_value=100, default=0)
    On_Time = 'On Time'
    At_Risk = 'At Risk'
    Delayed = 'Delayed'
    Status_Choice = (
        (On_Time, 'On Time'),
        (At_Risk, 'At Risk'),
        (Delayed, 'Delayed'),
    )

    Status = models.CharField(max_length=10, choices=Status_Choice, default='On_Time')
    Archive = models.BooleanField(default=False)


    def __str__(self):
        return self.Name

class Team(models.Model):
    TeamName = models.CharField(max_length=100, blank=True, default = '')
    Poc1 = models.CharField(max_length=100,blank=True, default='')
    Poc1_email = models.EmailField(max_length=100,blank=True, default='')
    Poc2 = models.CharField(max_length=100,blank=True, default='')
    Poc2_email = models.EmailField(max_length=100,blank=True, default='')
    Time_Delta_For_Warning = models.IntegerField(blank=True,default=7)
    completed = IntegerRangeField(min_value=0, max_value=100, default=0)
    On_Time = 'On Time'
    At_Risk = 'At Risk'
    Delayed = 'Delayed'
    Status_Choice = (
        (On_Time, 'On Time'),
        (At_Risk, 'At Risk'),
        (Delayed, 'Delayed'),
    )

    Status = models.CharField(max_length=10, choices=Status_Choice, default='On_Time')
    Product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.TeamName

class Task(models.Model):
    TaskName = models.CharField(max_length=100,blank=True, default='')
    StartDate = models.DateField(blank=True, null=True)
    EndDate = models.DateField(blank=True, null=True)
    CompleteDate = models.DateField(blank=True, null=True)
    DependentTask = models.CharField(max_length=250,blank=True, default='')
    Warning = models.BooleanField(default=False)
    Alert = models.BooleanField(default=False)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, null=True)
    IsPostLaunch = models.BooleanField(default=False)
    AssignedUser = models.CharField(max_length=250, blank=True, default='')


    def __str__(self):
        return self.TaskName

class TaskSta(models.Model):
    post = models.TextField(default='')
    created = models.DateTimeField(auto_now_add=True)
    Task = models.ForeignKey(Task, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, null=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.post

class DeviceHistory(models.Model):
    Completed = IntegerRangeField(min_value=0, max_value=100, default=0)
    Created = models.DateTimeField(auto_now_add=True)
    device = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)

class TeamHistory(models.Model):
    Delayed = models.DecimalField(max_digits=5,decimal_places=2, default = 0)
    Completed = models.DecimalField(max_digits=5,decimal_places=2, default = 0)
    DueSoon = models.DecimalField(max_digits=5,decimal_places=2, default = 0)
    OnTime = models.DecimalField(max_digits=5,decimal_places=2, default = 0)
    Created = models.DateTimeField(auto_now_add=True)
    device = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    team = models.OneToOneField(Team,blank=True, on_delete=models.CASCADE, default='')

class DashboardControlDevice(models.Model):
    Device = models.OneToOneField(Product,blank=True, on_delete=models.CASCADE, default='')

class DefaultDevice(models.Model):
    Name = models.CharField(max_length=100, default='Default')

    def __str__(self):
        return self.Name

class DefaultTeam(models.Model):
    Name = models.CharField(max_length=100, blank=True, default = '')
    Poc1 = models.CharField(max_length=100,blank=True, default='')
    Poc1_email = models.EmailField(max_length=100,blank=True, default='')
    Poc2 = models.CharField(max_length=100,blank=True, default='')
    Poc2_email = models.EmailField(max_length=100,blank=True, default='')
    Device = models.ForeignKey(DefaultDevice, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.Name

class DefaultTask(models.Model):
    Name = models.CharField(max_length=100, blank=True, default='')
    StartDelta = models.IntegerField(default=0,blank=True, null=True)
    EndDelta = models.IntegerField(default=0,blank=True,null=True)
    DependentTask = models.CharField(max_length=250, blank=True, default='')
    IsPostLaunch = models.BooleanField(default=False)
    AssignedUser = models.CharField(max_length=250, blank=True, default='')
    Team = models.ForeignKey(DefaultTeam, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.Name

Tracker/login/templates/login/change_password.html
{% extends 'base.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

Tracker/login/templates/login/devicesummaryHA.html
{% extends 'base.html' %}

{%block head%}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/data.js"></script>
<script src="https://code.highcharts.com/modules/drilldown.js"></script>



{% endblock%}

{%block content%}

{%if perms.mobile.is_strategic %}
<ul class="nav navbar-nav">
    <li><a href="/mobile/">Strategic Projects</a></li>
</ul>
{% endif %}
<ul class="nav navbar-nav">
    <li><a href="/login/summary">HA/HE</a></li>
</ul>

<ul class="nav navbar-nav">
    <li><a href="/general/">Mobile</a></li>
</ul>

<ul class="nav navbar-nav">
    <li><a href="/others/">Other Projects</a></li>
</ul>

{% endblock%}

{% block body %}

<div class="container-fluid" >

<div class="btn-group" role="group" aria-label="Basic example">
  <button type="button" class="btn btn-secondary" onclick="location.href='/login/homepage/HA/'">HA</button>
  <button type="button" class="btn btn-secondary" onclick="location.href='/login/homepage/HE/'">HE</button>
  <!--<button type="button" class="btn btn-secondary" >Mobile</button>-->
</div>

    <h2 align = "center">HA Overall Status</h2>
<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
    <p></p>
    <p></p>
    <h2 align = "center">HA Team Status by product</h2>


  <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
      {% for device in Device%}
      {% if forloop.counter <= 5 %}
    <button type="button" class="btn btn-secondary" onclick="location.href='/login/homepage/HA/{{device.id}}/'">{{device.Name}}</button>
    {% endif%}
    {%endfor%}

        {% if counter > 5%}
<div class="btn-group" role="group" aria-label="Button group with nested dropdown">
  <div class="btn-group" role="group">
    <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Dropdown
    </button>
    <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
    {% for device in Device%}
    {% if forloop.counter > 5 %}
      <a class="dropdown-item" onclick="location.href='/login/homepage/HA/{{device.id}}/'">{{device.Name}}</a>
      {% endif%}
      {%endfor%}
    </div>
  </div>
</div>
        {% endif%}
  </div>


<div id="container1" style="min-width: 310px; height: 400px; margin: 0 auto"></div>

</div>

<script type="text/javascript">
    Highcharts.chart('container', {
    chart: {
        type: 'column'
    },
    title: {
        text: 'Overall % Readiness HA Products'
    },
    subtitle: {
        text: 'Click the columns to view week over week update'
    },
    xAxis: {
        type: 'category'
    },
    yAxis: {
        title: {
            text: 'Completion %'
        }

    },
    legend: {
        enabled: false
    },
    plotOptions: {
        series: {
            borderWidth: 0,
            dataLabels: {
                enabled: true,
                format: '{point.y:.1f}%'
            }
        }
    },

    tooltip: {
        headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
        pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y:.2f}%</b> of total<br/>'
    },

    series: [{
        name: 'Products',
        colorByPoint: true,
        data: [
{% for D in Device %}
  {%if D.Archive == False %}
        {
            name: '{{D.Name}}',
            y: {{D.completed}},
            drilldown: '{{D.Name}}'
        },
  {%endif%}
{% endfor%}
        ]
    }],
    drilldown: {
        series: [
{% for D in Device %}
{%if D.Archive == False %}
        {
            name: '{{D.Name}}',
            id: '{{D.Name}}',
            data: [
            {%for z in D.devicehistory_set.all%}
                [
                    'Week #{{z.Created.isocalendar.1}}, {{z.Created|date:"M"}}',
                    {{z.Completed}}
                ],
            {%endfor%}
            ]
        },
  {%endif%}
{% endfor%}

        ]
    }
});
</script>
<script type="text/javascript">
  Highcharts.chart('container1', {
    chart: {
        type: 'column'
    },
    title: {
        text: '{{selectedDevice}} Team Status'
    },
    xAxis: {
        categories: ['Product Readiness', 'Video Content', 'Digital Content', 'Call Center Training', 'Call Center Operations', 'Product Support', 'Warehouse',
        'Field Service', 'Tech Support', 'Service Marketing', 'Service Training', 'Parts']
    },
    yAxis: {
        min: 0,
        title: {
            text: 'Total fruit consumption'
        },
        stackLabels: {
            enabled: true,
            style: {
                fontWeight: 'bold',
                color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
            }
        }
    },
    legend: {
        align: 'right',
        x: -30,
        verticalAlign: 'top',
        y: 25,
        floating: true,
        backgroundColor: (Highcharts.theme && Highcharts.theme.background2) || 'white',
        borderColor: '#CCC',
        borderWidth: 1,
        shadow: false
    },
    tooltip: {
        headerFormat: '<b>{point.x}</b><br/>',
        pointFormat: '{series.name}: {point.y}<br/>Total: {point.stackTotal}'
    },
    plotOptions: {
        column: {
            stacking: 'normal',
            dataLabels: {
                enabled: true,
                color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white'
            }
        }
    },
    series: [{
        name: 'Delayed',
        data: {{Delayed|safe}},
        color: 'red'
    }, {
        name: 'Due Soon',
        data: {{DueSoon|safe}},
        color: 'orange'
    }, {
        name: 'Completed',
        data: {{Completed|safe}},
        color: 'green'
    },
    {
        name: 'OnTime',
        data: {{OnTime|safe}},
        color: 'blue',
        visible: false
    },]
});


</script>
{% endblock %}

Tracker/login/templates/login/homepageHA.html
{% extends 'base.html' %}

{%block head%}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/data.js"></script>
<script src="https://code.highcharts.com/modules/drilldown.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>


{% endblock%}

{%block content%}

{%if perms.mobile.is_strategic %}
<ul class="nav navbar-nav">
    <li><a href="/mobile/">Strategic Projects</a></li>
</ul>
{% endif %}
<ul class="nav navbar-nav">
    <li><a href="/login/summary">HA/HE</a></li>
</ul>

<ul class="nav navbar-nav">
    <li><a href="/general/">Mobile</a></li>
</ul>

<ul class="nav navbar-nav">
    <li><a href="/others/">Other Projects</a></li>
</ul>

{% endblock%}

{% block body %}

<div class="container-fluid" >

<div class="btn-group" role="group" aria-label="Basic example">
  <button type="button" class="btn btn-secondary" onclick="location.href='/login/homepage/HA/'">HA</button>
  <button type="button" class="btn btn-secondary" onclick="location.href='/login/homepage/HE/'">HE</button>
  <!--<button type="button" class="btn btn-secondary" >Mobile</button>-->
</div>
<h2 align = "center">HA Overall Status</h2>
<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
        <p></p>
    <p></p>
<h2 align = "center">HA Team Status by product</h2>
  <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
      {% for device in Devices%}
      {% if forloop.counter <= 5 %}
    <button type="button" class="btn btn-secondary" onclick="location.href='/login/homepage/HA/{{device.id}}/'">{{device.Name}}</button>
    {% endif%}
    {%endfor%}

        {% if counter > 5%}
<div class="btn-group" role="group" aria-label="Button group with nested dropdown">
  <div class="btn-group" role="group">
    <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Dropdown
    </button>
    <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
    {% for device in Devices%}
    {% if forloop.counter > 5 %}
      <a class="dropdown-item" onclick="location.href='/login/homepage/HA/{{device.id}}/'">{{device.Name}}</a>
      {% endif%}
      {%endfor%}
    </div>
  </div>
</div>
        {% endif%}
  </div>
</div>


<script type="text/javascript">
    Highcharts.chart('container', {
    chart: {
        type: 'column'
    },
    title: {
        text: 'Overall % Readiness HA Products'
    },
    subtitle: {
        text: 'Click the columns to view week over week update'
    },
    xAxis: {
        type: 'category'
    },
    yAxis: {
        title: {
            text: 'Completion %'
        }

    },
    legend: {
        enabled: false
    },
    plotOptions: {
        series: {
            borderWidth: 0,
            dataLabels: {
                enabled: true,
                format: '{point.y:.1f}%'
            }
        }
    },

    tooltip: {
        headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
        pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y:.2f}%</b> of total<br/>'
    },

    series: [{
        name: 'Products',
        colorByPoint: true,
        data: [
{% for D in Devices %}
  {%if D.Archive == False %}
        {
            name: '{{D.Name}}',
            y: {{D.completed}},
            drilldown: '{{D.Name}}'
        },
  {%endif%}
{% endfor%}
        ]
    }],
    drilldown: {
        series: [
{% for D in Devices %}
{%if D.Archive == False %}
        {
            name: '{{D.Name}}',
            id: '{{D.Name}}',
            data: [
            {%for z in D.devicehistory_set.all%}
                [
                    'Week #{{z.Created.isocalendar.1}}, {{z.Created|date:"M"}}',
                    {{z.Completed}}
                ],
            {%endfor%} 
            ]
        },
  {%endif%}
{% endfor%}

        ]
    }
});
</script>
{% endblock %}

Tracker/login/templates/login/login.html
{% extends 'base.html' %}

{% block body %}
<div class="container" align="center">
    <!--<div class="row">-->
        <!--<div class="col-md-offset-3 col-md-6">-->

    <h2>Login</h2>
    <form method = "post">
        {% csrf_token%}
        {{ form.as_p }}
        <button class= "btn btn-success" type ="submit">Login</button>
    </form>
        <!--</div>-->
    <!--</div>-->
</div>
{% endblock %}

Tracker/login/templates/login/notasuperuser.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}

{% block body %}
<div class ='container'>
    <h1> You are not a super user and cannot use this feature</h1>
</div>
{% endblock %}

Tracker/login/templates/login/reg_form.html
{% extends 'base.html' %}

{% block body %}
<div  class="container"  align="center">
    <h1>Register</h1>
    <form method = "POST">
      {% csrf_token %}
      {{ form.as_p }}
        <button class= "btn btn-success" type="submit">Submit</button>
    </form>
</div>
{% endblock %}