Tracker/Tracker/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from Tracker import views

urlpatterns = [
    url(r'^$', views.login_redirect, name ='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include('login.urls')),
    url(r'^mobile/', include('mobile.urls')),
    url(r'^general/', include('general.urls')),
    url(r'^others/', include('others.urls')),
    url(r'^hahe/', include('hahe.urls')),
]

Tracker/hahe/urls.py
from django.conf.urls import url, include
from . import views
from hahe.views import (
ProductView, IntermediateView, DetailView, AddDeviceView, ExcelView, DetailExcelView, HomepageView, DeviceSummaryView,
HomepageHAView, HomepageHEView, DeviceSummaryHAView, DeviceSummaryHEView
)

urlpatterns = [
    url(r'^$', ProductView.as_view(), name='haheproduct'),
    url(r'^homepage/$', HomepageView.as_view(), name='haheHomepage'),
    url(r'^homepage/HA/$', HomepageHAView.as_view(), name='haheHomepageHA'),
    url(r'^homepage/HE/$', HomepageHEView.as_view(), name='haheHomepageHE'),
    url(r'^homepage/(?P<pk>\d+)/$', DeviceSummaryView.as_view(), name='DeviceSummary'),
    url(r'^homepage/HA/(?P<pk>\d+)/$', DeviceSummaryHAView.as_view(), name='DeviceSummaryHA'),
    url(r'^homepage/HE/(?P<pk>\d+)/$', DeviceSummaryHEView.as_view(), name='DeviceSummaryHE'),
    url(r'^(?P<pk>\d+)/$', IntermediateView.as_view(), name='haheintermediate'),
    url(r'^teams/(?P<id>\d+)/$', DetailView.as_view(), name='hahedetail'),
    url(r'^defaulttemplate/$', AddDeviceView.as_view(), name='haheAddDevice'),
    url(r'^excel/$', ExcelView.as_view(), name='haheExcel'),
    url(r'^(?P<pk>\d+)/detailexcel/$', DetailExcelView.as_view(), name='haheDetailExcel'),
]

Tracker/others/urls.py
from django.conf.urls import url, include
from . import views
from others.views import (
ProductView, IntermediateView, DetailView, ExcelView, DetailExcelView
)

urlpatterns = [
    url(r'^$', ProductView.as_view(), name='othersproduct'),
    url(r'^(?P<pk>\d+)/$', IntermediateView.as_view(), name='othersintermediate'),
    url(r'^teams/(?P<id>\d+)/$', DetailView.as_view(), name='othersdetail'),
    url(r'^excel/$', ExcelView.as_view(), name='othersExcel'),
    url(r'^(?P<pk>\d+)/detailexcel/$', DetailExcelView.as_view(), name='othersDetailExcel'),
]

Tracker/others/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _

from django.db import models

# Create your models here.

class IntegerRangeField(models.IntegerField):
    def __init__(self, verbose_name=None, name=None, min_value=None, max_value=None, **kwargs):
        self.min_value, self.max_value = min_value, max_value
        models.IntegerField.__init__(self, verbose_name, name, **kwargs)
    def formfield(self, **kwargs):
        defaults = {'min_value': self.min_value, 'max_value':self.max_value}
        defaults.update(kwargs)
        return super(IntegerRangeField, self).formfield(**defaults)

class category(models.Model):
    Name = models.CharField(max_length=100, default = '')

    def __str__(self):
        return self.Name

class Product(models.Model):
    Name = models.CharField(max_length=100, default = '')
    ProductDescription = models.CharField(max_length=100, default='')
    LaunchDate = models.DateField(blank=True, null=True)
    completed = IntegerRangeField(min_value=0, max_value=100, default=0)
    On_Time = 'On Time'
    At_Risk = 'At Risk'
    Delayed = 'Delayed'
    Status_Choice = (
        (On_Time, 'On Time'),
        (At_Risk, 'At Risk'),
        (Delayed, 'Delayed'),
    )

    Status = models.CharField(max_length=10, choices=Status_Choice, default='On_Time')
    Archive = models.BooleanField(default=False)
    Category = models.ForeignKey(category, on_delete=models.CASCADE, null=True)


    def __str__(self):
        return self.Name

class Team(models.Model):
    TeamName = models.CharField(max_length=100, blank=True, default = '')
    Poc1 = models.CharField(max_length=100,blank=True, default='')
    Poc1_email = models.EmailField(max_length=100,blank=True, default='')
    Poc2 = models.CharField(max_length=100,blank=True, default='')
    Poc2_email = models.EmailField(max_length=100,blank=True, default='')
    Time_Delta_For_Warning = models.IntegerField(blank=True,default=7)
    completed = IntegerRangeField(min_value=0, max_value=100, default=0)
    On_Time = 'On Time'
    At_Risk = 'At Risk'
    Delayed = 'Delayed'
    Status_Choice = (
        (On_Time, 'On Time'),
        (At_Risk, 'At Risk'),
        (Delayed, 'Delayed'),
    )

    Status = models.CharField(max_length=10, choices=Status_Choice, default='On_Time')
    Product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.TeamName

class Task(models.Model):
    TaskName = models.CharField(max_length=100,blank=True, default='')
    StartDate = models.DateField(blank=True, null=True)
    EndDate = models.DateField(blank=True, null=True)
    CompleteDate = models.DateField(blank=True, null=True)
    DependentTask = models.CharField(max_length=250,blank=True, default='')
    Warning = models.BooleanField(default=False)
    Alert = models.BooleanField(default=False)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, null=True)
    IsPostLaunch = models.BooleanField(default=False)


    def __str__(self):
        return self.TaskName

class TaskStat(models.Model):
    post = models.TextField(default='')
    created = models.DateTimeField(auto_now_add=True)
    Task = models.ForeignKey(Task, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, null=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.post

Tracker/others/forms.py
from django import forms
from others.models import (
Task, TaskStat
)

class Status_form(forms.ModelForm):
    post = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Write a status...'
        }
    ))

    class Meta:
        model = TaskStat
        fields = ('post',)

class Completion_Date_form(forms.ModelForm):
    CompleteDate = forms.DateField(required=False,widget=forms.DateInput(attrs={'class':'datepicker'}))
    class Meta:
        model = Task
        fields = ('CompleteDate',)

Tracker/others/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from others.forms import (
Status_form, Completion_Date_form
)
from django.views.generic import TemplateView, ListView
from others.models import (
Product, Team, Task, TaskStat, category
)
import datetime
from datetime import timedelta
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
# Create your views here.

class DetailExcelView (LoginRequiredMixin,TemplateView ):
    template_name = 'others/detailexcel.html'
    login_url = '/login/auth/'
    def get(self, request, pk):
        devices = Product.objects.get(pk=pk)
        teams = devices.team_set.all().order_by('id')
        NumberOfTasksArray = []
        TaskInstance = []
        for team in teams:
            tasks = team.task_set.all().order_by('id')
            TaskInstance.append(tasks)
            NumberOfTasks = 1
            for task in tasks:
                NumberOfTasks = NumberOfTasks + 1
            NumberOfTasksArray.append(NumberOfTasks)

        zipped_data = zip(teams, NumberOfTasksArray, TaskInstance)

        args = {'devices':devices, 'teams':teams, 'zip':zipped_data}
        return render(request, self.template_name, args )

class ExcelView (LoginRequiredMixin,TemplateView ):
    template_name = 'others/excel.html'
    login_url = '/login/auth/'
    def get(self, request):
        devices = Product.objects.all().order_by("LaunchDate")
        try:
            device_latest = Product.objects.order_by('-id')[0]
        except:
            print ("Error")
            args = {'Device': devices,}
            return render (request, self.template_name, args, )
        cat = category.objects.all()
        teams = device_latest.team_set.all().order_by('id')

        for device in devices:
            if device.Archive == False:
                teams = device.team_set.all().order_by('id')
                OverallTasks = 0
                OverallCompletedTasks = 0
                for team in teams:
                    today = datetime.date.today()
                    tasks = team.task_set.all().order_by('id')
                    Taskcompleted = 0
                    NumberOfTasks = 0
                    for task in tasks:
                        OverallTasks = OverallTasks+1
                        NumberOfTasks = NumberOfTasks + 1
                        if task.CompleteDate:
                            task.Warning = False
                            task.Alert = False
                            OverallCompletedTasks = OverallCompletedTasks +1
                            Taskcompleted = Taskcompleted + 1
                        if task.EndDate:
                            Time_delta = task.EndDate - today
                            if Time_delta < timedelta(team.Time_Delta_For_Warning) and Time_delta > timedelta(0) and \
                                    not task.CompleteDate:
                                task.Warning = True
                                team.Status = 'At Risk'
                            elif Time_delta < timedelta(0) and not task.CompleteDate:
                                task.Warning = False
                                task.Alert = True
                        else:
                            Time_delta = None
                        task.save()

                    for task in tasks:
                        if task.Alert == True:
                            team.Status = 'Delayed'
                        task.save()

                    if NumberOfTasks != 0:
                        PercentCompleted = int((Taskcompleted * 100) / NumberOfTasks)
                        team.completed = PercentCompleted
                        team.save()
                if OverallTasks!= 0:
                    OverallCompletedPercent = int((OverallCompletedTasks * 100)/OverallTasks)
                    device.completed = OverallCompletedPercent
                    device.save()



        args = {'Device': devices, 'teams':teams, 'cat':cat}
        return render (request, self.template_name, args, )

class ProductView(LoginRequiredMixin,ListView):
    template_name = 'others/summary.html'
    login_url = '/login/auth/'
    def get(self, request):
        devices = Product.objects.all().order_by("LaunchDate")
        cat = category.objects.all()
        try:
            device_latest = Product.objects.order_by('-id')[0]
        except:
            print ("Error")
            args = {'Device': devices,}
            return render (request, self.template_name, args, )
        else:
            print ("Shreyas is here")

        teams = device_latest.team_set.all().order_by('id')

        for device in devices:
            if device.Archive == False:
                teams = device.team_set.all().order_by('id')
                OverallTasks = 0
                OverallCompletedTasks = 0
                for team in teams:
                    today = datetime.date.today()
                    tasks = team.task_set.all().order_by('id')
                    Taskcompleted = 0
                    NumberOfTasks = 0
                    for task in tasks:
                      if task.IsPostLaunch == False:
                        OverallTasks = OverallTasks+1
                        NumberOfTasks = NumberOfTasks + 1
                        if task.CompleteDate:
                            task.Warning = False
                            task.Alert = False
                            OverallCompletedTasks = OverallCompletedTasks +1
                            Taskcompleted = Taskcompleted + 1
                        if task.EndDate:
                            Time_delta = task.EndDate - today
                            if Time_delta < timedelta(team.Time_Delta_For_Warning) and Time_delta > timedelta(0) and \
                                    not task.CompleteDate:
                                task.Warning = True
                                team.Status = 'At Risk'
                            elif Time_delta < timedelta(0) and not task.CompleteDate:
                                task.Warning = False
                                task.Alert = True
                        else:
                            Time_delta = None
                        task.save()
                      else:
                        if task.CompleteDate:
                            task.Warning = False
                            task.Alert = False
                        if task.EndDate:
                            Time_delta = task.EndDate - today
                            if Time_delta < timedelta(team.Time_Delta_For_Warning) and Time_delta > timedelta(0) and \
                                    not task.CompleteDate:
                                task.Warning = True
                                team.Status = 'At Risk'
                            elif Time_delta < timedelta(0) and not task.CompleteDate:
                                task.Warning = False
                                task.Alert = True

                    for task in tasks:
                        if task.Alert == True:
                            team.Status = 'Delayed'
                        task.save()

                    if NumberOfTasks != 0:
                        PercentCompleted = int((Taskcompleted * 100) / NumberOfTasks)
                        team.completed = PercentCompleted
                        team.save()
                if OverallTasks!= 0:
                    OverallCompletedPercent = int((OverallCompletedTasks * 100)/OverallTasks)
                    device.completed = OverallCompletedPercent
                    device.save()



        args = {'Device': devices, 'teams':teams, 'cat':cat}
        return render (request, self.template_name, args, )

class IntermediateView(LoginRequiredMixin,ListView):
    template_name = 'others/intermediate.html'
    login_url = '/login/auth/'

    def get(self, request, pk):
        devices = Product.objects.get(pk=pk)
        teams = devices.team_set.all().order_by('id')
        args = {'devices':devices, 'teams':teams}
        return render(request, self.template_name, args )

class DetailView (LoginRequiredMixin,TemplateView):
    template_name = 'others/detail.html'
    login_url = '/login/auth/'

    def get(self, request, id):

        teams = Team.objects.get(pk=id)
        device = teams.Product
        DeviceTeam = device.team_set.all().order_by('id')
        tasks = teams.task_set.all().order_by('id')
        today = datetime.date.today()
        form = []
        dateform = []
        taskTimeDelta = []
        Taskcompleted = 0
        NumberOfTasks = 0
        PercentCompleted = 0
        for task in tasks:
          if task.IsPostLaunch == False:
            form.append (Status_form())
            dateform.append(Completion_Date_form(instance=task))
            NumberOfTasks = NumberOfTasks + 1
            if task.CompleteDate:
                task.Warning = False
                task.Alert = False
                Taskcompleted = Taskcompleted + 1
            if task.EndDate:
                Time_delta = task.EndDate - today
                if Time_delta < timedelta(teams.Time_Delta_For_Warning) and Time_delta > timedelta(0) and \
                    not task.CompleteDate:
                    task.Warning = True
                    teams.Status = 'At Risk'
                elif Time_delta < timedelta(0) and not task.CompleteDate:
                    task.Warning = False
                    task.Alert = True
            else:
                Time_delta = None
            taskTimeDelta.append (Time_delta)
            task.save()
          else:
            if task.CompleteDate:
                task.Warning = False
                task.Alert = False
            if task.EndDate:
                Time_delta = task.EndDate - today
                if Time_delta < timedelta(teams.Time_Delta_For_Warning) and Time_delta > timedelta(0) and \

Tracker/others/templates/others/detail.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block head %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.0/css/bootstrap-datepicker.css">
<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.0/css/bootstrap-datepicker.min.css">
<!--<script src="{% static 'js/moment.min.js' %}"></script>-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.0/js/bootstrap-datepicker.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.0/js/bootstrap-datepicker.min.js"></script>

<script>
    $(document).ready(function() {
  $(".search").keyup(function () {
    var searchTerm = $(".search").val();
    var listItem = $('.results tbody').children('tr');
    var searchSplit = searchTerm.replace(/ /g, "'):containsi('")

  $.extend($.expr[':'], {'containsi': function(elem, i, match, array){
        return (elem.textContent || elem.innerText || '').toLowerCase().indexOf((match[3] || "").toLowerCase()) >= 0;
    }
  });

  $(".results tbody tr").not(":containsi('" + searchSplit + "')").each(function(e){
    $(this).attr('visible','false');
  });

  $(".results tbody tr:containsi('" + searchSplit + "')").each(function(e){
    $(this).attr('visible','true');
  });

  var jobCount = $('.results tbody tr[visible="true"]').length;
    $('.counter').text(jobCount + ' item');

  if(jobCount == '0') {$('.no-result').show();}
    else {$('.no-result').hide();}
		  });
});

</script>

<script>
$(document).ready(function(){
    $('.datepicker').datepicker();
});
</script>

<style>

.results tr[visible='false'],
.no-result{
  display:none;
}

.results tr[visible='true']{
  display:table-row;
}

.counter{
  padding:8px;
  color:#ccc;
}
</style>

{% endblock %}

{%block content%}
<ul class="nav navbar-nav">
    <li><a href="/others/">Other Projects</a></li>
</ul>

<ul class="nav navbar-nav">
    <li><a href="/others/{{device.id}}/">Team Status</a></li>
</ul>

{% for team in DeviceTeam%}

<ul class="nav navbar-nav">
    <li><a href="/others/teams/{{team.id}}/">{{team.TeamName}}</a></li>
</ul>

{% endfor %}

{% endblock %}

{% block body %}
<div class="container">
    {% for task in tasks%}
        {%if task.Alert%}

    <div class="alert alert-danger alert-dismissable fade in">
    <a class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>Delayed!</strong> - {{task.TaskName}}!
    </div>
    {% endif %}
    {% endfor %}

    {% for task in tasks%}
    {% if task.Warning %}

	  <div class="alert alert-warning alert-dismissable fade in">
    <a class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>Due Soon!</strong> {{task.TaskName}} is in less
          than {{teams.Time_Delta_For_Warning}} days!

    {% endif %}
    {% endfor %}
</div>
    <div class="container">
<h2 align="center">Completion %</h2>
<div class="progress">
  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40"
  aria-valuemin="0" aria-valuemax="100" style="width:{{PercentCompleted}}%">
    {{PercentCompleted}}% Complete
  </div>
</div>
</div>

<div class="container">
    <h1>{{teams.TeamName}} status</h1>
        <div class="form-group pull-right">
    <input type="text" class="search form-control" placeholder="Search Tasks">
</div>
<span class="counter pull-right"></span>
    <table class="table table-striped table-hover table-bordered results">
        <thead>
            <tr>
                <th><h4>Tasks</h4></th>
                <th><h4>Delayed/Due Soon</h4></th>
                <th><h4>Due Date</h4></th>
                <th><h4>Completed Date</h4></th>
                <th><h4>Status Details</h4></th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th><h4>Tasks</h4></th>
                <th><h4>Delayed/Due Soon</h4></th>
                <th><h4>Due Date</h4></th>
                <th><h4>Completed Date</h4></th>
                <th><h4>Status Details</h4></th>
            </tr>
        </tfoot>
        <tbody>
        {% for i,j,k,l in zipped_data %}
        <tr>
            <th>
                <h4>{{ i.TaskName}}</h4>
                    {% if i.IsPostLaunch %}
                <h6><font color="#0000cc">POST LAUNCH TASK</font></h6>
                    {%endif%}
                    <h6><font color="#0000cc">{{i.DependentTask}}</font></h6></th>
            {%if i.Alert %}
            <th align="center"><span class="glyphicon glyphicon-minus-sign" style="color:red" aria-hidden="true"></span></th>
            {%elif i.Warning %}
            <th align="center"><span class="glyphicon glyphicon-exclamation-sign" style="color:orange" aria-hidden="true"></span></th>
            {%else%}
            <th></th>
            {%endif%}
            <th>20{{i.EndDate|date:"y-m-d"}}
                {%if not i.CompleteDate %}
                    <p>(due in {{l.days}} days)</p>
                {% endif %}
            </th>

            <form method="post">
                     {% csrf_token %}
                <td>{{ k.CompleteDate}}</td>
                <td >
                        {{j.as_p}}
                        <button class="btn btn-success" name="{{forloop.counter}}submit" type="submit" &nbsp>Submit</button>
                        {% for post in i.taskstat_set.all %}
                          <p>{{ post.created|date:"m-d" }} <font color="#0000cc">
                              ({{ post.user.get_username}}):</font>
                              {{ post.post }}</p>
                        {% endfor %}
            </form>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

Tracker/others/templates/others/detailexcel.html
{% extends 'base.html' %}

{% block head %}
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script>
    $(document).ready(function() {
  $("#btnExport").click(function(e) {
    e.preventDefault();

    //getting data from our table
    var data_type = 'data:application/vnd.ms-excel';
    var table_div = document.getElementById('table_wrapper');
    var table_html = table_div.outerHTML.replace(/ /g, '%20');

    var a = document.createElement('a');
    a.href = data_type + ', ' + table_html;
    a.download = 'exported_table_' + Math.floor((Math.random() * 9999999) + 1000000) + '.xls';
    a.click();
  });
});

</script>
{% endblock %}

{%block content%}
<ul class="nav navbar-nav">
    <li><a href="/others/">Other Projects</a></li>
</ul>

<ul class="nav navbar-nav">
    <li><a href="/hahe/">HA/HE</a></li>
</ul>

<ul class="nav navbar-nav">
    <li><a href="/general/">Mobile</a></li>
</ul>

<ul class="nav navbar-nav">
    <li><a href="/others/excel">Back</a></li>
</ul>
{% endblock %}

{% block body %}

<div class ="container">
    <h1>{{devices.Name}} - Detailed Status</h1>
 <button id="btnExport">Export to xls</button>
  <br />
  <br />
  <div id="table_wrapper">
    <table border="1" cellspacing="0" bordercolor="#222" id="list">
      <tbody>
        <tr class="header">
							<th>Team</th>
							<th>POC</th>
							<th>Tasks</th>
							<th>Start Date</th>
							<th>Target Complete Date</th>
							<th>Actual Date Complete</th>
                            <th>Status/Details</th>
							<th>Status</th>
							<th>Completion Rate</th>
        </tr>

        {% for i,j,k in zip%}
        <tr>
            <th rowspan={{j}}>{{i.TeamName}}</th>
            <th rowspan={{j}}><p>{{i.Poc1}}</p> <p>{{i.Poc2}}</p></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            {% if i.completed == 100 %}
            <th rowspan={{j}}>Completed</th>
            {% else%}
            <th rowspan={{j}}>{{ i.Status }}</th>
            {% endif %}
            <th rowspan={{j}}>{{i.completed}}</th>

        </tr>
                    {% for task in k%}
        <tr>
            <th> {{task.TaskName}}</th>
            <th>{{task.StartDate}}</th>
            <th>{{task.EndDate}}</th>
            <th>{{task.CompleteDate}}</th>
            <th>
                <p>
                <p>{%for post in task.taskstat_set.all%}
                {{ post.created|date:"m-d" }} <font color="#0000cc">
                    ({{ post.user.get_username}}):</font>
                {{ post.post }}

                {% endfor %}</p>
            </th>
            </tr>
            {% endfor %}
        {% endfor %}

      </tbody>
    </table>
  </div>
</div>


        {% endblock %}

Tracker/others/templates/others/excel.html
{% extends 'base.html' %}

{% block head %}
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script>

{%for category in cat %}
    $(document).ready(function() {
  $("#btnExport{{forloop.counter}}").click(function(e) {
    e.preventDefault();

    //getting data from our table
    var data_type = 'data:application/vnd.ms-excel';
    var table_div = document.getElementById('table_wrapper{{forloop.counter}}');
    var table_html = table_div.outerHTML.replace(/ /g, '%20');

    var a = document.createElement('a');
    a.href = data_type + ', ' + table_html;
    a.download = 'exported_table_' + Math.floor((Math.random() * 9999999) + 1000000) + '.xls';
    a.click();
  });
});

{%endfor %}
</script>
{% endblock %}

{%block content%}
<ul class="nav navbar-nav">
    <li><a href="/others/">Other Projects</a></li>
</ul>

<ul class="nav navbar-nav">
    <li><a href="/hahe/">HA/HE</a></li>
</ul>

<ul class="nav navbar-nav">
    <li><a href="/general/">Mobile</a></li>
</ul>


{% endblock %}

{% block body %}
<div class ="container">

    {%for category in cat %}
    <p></p>
    <p></p>
    <h2 align ="center">{{category.Name}}</h2>
 <button id="btnExport{{forloop.counter}}">Export to xls</button>
  <br />
  <br />
  <div id="table_wrapper{{forloop.counter}}">
    <table border="1" cellspacing="0" bordercolor="#222" id="list">
      <tbody>
              <tr class="header">
							<th>Product Description</th>
							<th>Project</th>
							<th>Target Launch Date</th>
							<th>Overall% Ready</th>
							{% for team in category.product_set.first.team_set.all%}
							<th>{{team.TeamName}}</th>
							{% endfor%}

              </tr>
                           {% for Device in category.product_set.all %}
                        {% if Device.Archive == False %}
                        <tr>
							<td align="center" onclick="location.href='/others/{{Device.id}}/detailexcel/'"
                            style="cursor:pointer">{{Device.ProductDescription}}</td>
							<td align="center" onclick="location.href='/others/{{Device.id}}/detailexcel/'"
                            style="cursor:pointer">{{Device.Name}}</td>
							<td align="center" onclick="location.href='/others/{{Device.id}}/detailexcel/'"
                            style="cursor:pointer">{{Device.LaunchDate|date:"m-d-y"}}</td>
                            {% if Device.completed == 0 %}
                            <td align="center" onclick="location.href='/others/{{Device.id}}/detailexcel/'"
                            style="cursor:pointer">Not Started</td>
                            {% else %}
							<td align="center" onclick="location.href='/others/{{Device.id}}/detailexcel/'"
                            style="cursor:pointer">{{Device.completed}}</td>
                            {% endif %}
							{% for team in Device.team_set.all%}
                                {% if team.completed == 100 %}
                                <td align="center" onclick="location.href='/others/{{Device.id}}/detailexcel/'"
                            style="cursor:pointer"><font color="green">Completed</font></td>
                                {% else%}
                                {% if team.Status == "At Risk" %}
                                <th align="center" onclick="location.href='/others/{{Device.id}}/detailexcel/'"
                            style="cursor:pointer"><font color="orange">At Risk</font></th>
                                {% elif team.Status == "Delayed" %}
                                <th align="center" onclick="location.href='/others/{{Device.id}}/detailexcel/'"
                            style="cursor:pointer"><font color="red">Delayed</font></th>
                                {% else %}
                                <th align="center" onclick="location.href='/others/{{Device.id}}/detailexcel/'"
                            style="cursor:pointer"><font color="blue">On Time</font></th>
                                {% endif %}
                                {% endif %}

							{% endfor%}

                        </tr>
                        {% endif %}
                    {% endfor%}
      </tbody>
    </table>
  </div>
    {% endfor%}
</div>

      {% endblock%}